version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/build

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
   
hooks:
  AfterInstall:
    - location: initialize.sh
      timeout: 3000
      runas: ec2-user
