version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/build

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
   
hooks:
  BeforeInstall:
    - location: /home/ec2-user/build/server_clear.sh
      timeout: 3000
      runas: ec2-user
  AfterInstall:
    - location: /home/ec2-user/build/initialize.sh
      timeout: 3000
      runas: ec2-user
  ApplicationStart:
    - location: /home/ec2-user/build/server_start.sh
      timeout: 3000
      runas: ec2-user
  ApplicationStop:
    - location: /home/ec2-user/build/server_stop.sh
      timeout: 3000
      runas: ec2-user
