version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec-2user/project_daily_auction/server/build/libs

hooks:
  BeforeInstall:
    - location: server_clear.sh
      timeout: 3000
      runas: root
  AfterInstall:
    - location: initialize.sh
      timeout: 3000
      runas: root
  ApplicationStart:
    - location: server_start.sh
      timeout: 3000
      runas: root
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 3000
      runas: root
