spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://daily-auction-rds.cqig7mn7hzad.ap-northeast-2.rds.amazonaws.com:13306/dailyAuction?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: ${RDS_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true;
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: yeogiyo007@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 767519204317-5d6r3imorm6euetge3oq1nkvbdgihnik.apps.googleusercontent.com
            clientSecret: ${CLIENT_SECRET_GOOGLE}
            scope:
              - email
          kakao:
            clientId: 817c5fbdef0e3b673a764e0b464e6acb
            clientSecret: ${CLIENT_SECRET_KAKAO}
            redirect-uri: http://server.dailyauction.site:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: Kakao


jwt:
  key:
    secret: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 1440

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: daily-auction-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE