name: Deploy to EC2

on:
  push:
    branches:
      - BE-dev-server

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install openssh-client -y

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            cd project_daily_auction
            git fetch
            git checkout BE-dev-server
            git pull
            cd server
            ./gradlew clean build
            ./gradlew build
