name: Deploy to S3 - develop mode

on:
  push:
    branches:
      - FE-dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout code
        uses: actions/checkout@master

      - name: Install dependencies and build client
        run : cd client
              npm i
              npm run build

      - name: deploy to s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-2'
          SOURCE_DIR: 'build'
